// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjOvL4dJO9VFxMpjzNKKzpy1gl2gOCzHA',
    appId: '1:874860067770:web:dbb1d5de09e62d607afb83',
    messagingSenderId: '874860067770',
    projectId: 'bill-reminder-7ceee',
    authDomain: 'bill-reminder-7ceee.firebaseapp.com',
    databaseURL: 'https://bill-reminder-7ceee-default-rtdb.firebaseio.com',
    storageBucket: 'bill-reminder-7ceee.appspot.com',
    measurementId: 'G-WFXMKF3E5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmhcF5VbvbC6phLs7l0keurDDAEG-I0kY',
    appId: '1:874860067770:android:7661662650efa03e7afb83',
    messagingSenderId: '874860067770',
    projectId: 'bill-reminder-7ceee',
    databaseURL: 'https://bill-reminder-7ceee-default-rtdb.firebaseio.com',
    storageBucket: 'bill-reminder-7ceee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqYGfrX6oSdKyjZ5ndHzAhhrkbBc9vcf0',
    appId: '1:874860067770:ios:cb4e96076022fb007afb83',
    messagingSenderId: '874860067770',
    projectId: 'bill-reminder-7ceee',
    databaseURL: 'https://bill-reminder-7ceee-default-rtdb.firebaseio.com',
    storageBucket: 'bill-reminder-7ceee.appspot.com',
    iosClientId: '874860067770-rf95oquqland4db3ohda279r1ijt574t.apps.googleusercontent.com',
    iosBundleId: 'com.example.billReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqYGfrX6oSdKyjZ5ndHzAhhrkbBc9vcf0',
    appId: '1:874860067770:ios:7f4837a9543f0fa37afb83',
    messagingSenderId: '874860067770',
    projectId: 'bill-reminder-7ceee',
    databaseURL: 'https://bill-reminder-7ceee-default-rtdb.firebaseio.com',
    storageBucket: 'bill-reminder-7ceee.appspot.com',
    iosClientId: '874860067770-6q5q9rfbfrclserfulpmbfoh9qbqd8ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.billReminderApp.RunnerTests',
  );
}
